(function (global) {
    var TEMPLATES = {
        simple: {
            title: 'פשוט ATS',
            titleHe: 'פשוט ATS',
            titleEn: 'Simple ATS',
            subHe: 'יעל שמעוני · מורה',
            subEn: 'Yael Shimony · Teacher',
            thumb: 'lay-simple',
            layout: 'classic',
            skin: '',
            accent: '#1c1917',
            font: 'Heebo',
            bg: 'bg-preview-white',
            field: 'edu',
            preferredLang: 'he',
            he: {
                name: 'יעל שמעוני',
                title: 'מורה ללשון ולספרות',
                phone: '052-4412270',
                email: 'yael.shimony@example.com',
                location: 'רחובות',
                linkedin: 'linkedin.com/in/yaelshimony',
                summary: 'מורה עם ניסיון בהוראת לשון, בניית מערכים וליווי תלמידים. מסמך נקי שעובר סינון אוטומטי וגם נקרא היטב בעין.',
                experience: '2020 - נוכחי | תיכון גן רווה\nמורה ללשון ולספרות\n• בניית מערכי שיעור מותאמים והעלאת אחוזי הצלחה בבגרות.\n• ליווי מחנכת כיתה ושיתוף פעולה עם הורים וצוות מקצועי.\n\n2017 - 2020 | חטיבת ביניים אורט\nמורה לעברית\n• שילוב כלים דיגיטליים בהוראה ומעקב התקדמות אישי.',
                education: '2013 - 2017 | B.Ed. הוראת לשון\n2019 | תעודת הוראה לחטיבה עליונה',
                military: '2011 - 2013 | מש"קית חינוך',
                skills: 'הוראה, בניית מערכים, הנחיה, עבודת צוות, כלים דיגיטליים',
                languages: 'עברית (שפת אם), אנגלית (גבוהה)',
                references: ''
            },
            en: {
                name: 'Yael Shimony',
                title: 'Hebrew Language Teacher',
                phone: '052-4412270',
                email: 'yael.shimony@example.com',
                location: 'Rehovot',
                linkedin: 'linkedin.com/in/yaelshimony',
                summary: 'Teacher experienced in language instruction, lesson design, and student support. A clean one-column resume that reads well for people and ATS scans.',
                experience: '2020 - Present | Gan Raveh High School\nLanguage and literature teacher\n• Designed lesson plans and raised matriculation pass rates.\n• Homeroom support and partnership with parents and staff.\n\n2017 - 2020 | Ort Middle School\nHebrew teacher\n• Used digital tools in class and tracked individual progress.',
                education: '2013 - 2017 | B.Ed. Language Education\n2019 | Upper-secondary teaching certificate',
                military: '2011 - 2013 | Education NCO',
                skills: 'Teaching, lesson design, facilitation, teamwork, digital tools',
                languages: 'Hebrew (native), English (advanced)',
                references: ''
            }
        },
        charcoal: {
            title: 'קלאסי עם תמונה',
            titleHe: 'קלאסי עם תמונה',
            titleEn: 'Photo Classic',
            subHe: 'ג\'קסון אנדרסון · מנהל שיווק',
            subEn: 'Jackson Anderson · Marketing Manager',
            thumb: 'lay-charcoal',
            layout: 'charcoal',
            skin: '',
            accent: '#4c4c4c',
            font: 'Lato',
            bg: 'bg-preview-white',
            field: 'marketing',
            preferredLang: 'en',
            he: {
                name: 'ג\'קסון אנדרסון',
                title: 'מנהל שיווק',
                phone: '03-5550190',
                email: 'hello@reallygreatsite.com',
                location: 'תל אביב',
                linkedin: '',
                summary: 'מנהל שיווק עם ניסיון בקמפיינים למותג, חיזוק מכירות וצמיחה דיגיטלית בשווקים מקומיים ובינלאומיים.',
                experience: '2020 - 2023 | Borcello International Co.\nמנהל שיווק\n• הובלת קמפיינים משולבים בדיגיטל, קמעונאות וערוצי שותפים.\n• הגדלת פייפליין איכותי ושיפור המרה בקווי מוצר מרכזיים.\n• בניית דיווח להנהלה ולצוותי מכירות אזוריים.\n\n2019 - 2020 | Salford & Co.\nמנהל שיווק\n• אחריות על תוכניות השקה, בריפים יצירתיים ולוחות קמפיינים.\n• שותפות עם מכירות בערכות enablement, אירועים ומסרים.',
                education: '2016 - 2019 | Borcello University\nניהול שיווק\n\n2012 - 2016 | Rimberio University\nמנהל עסקים',
                military: '',
                skills: 'ניהול, מכירות שיווקיות, שיווק דיגיטלי, משא ומתן, חשיבה ביקורתית, מנהיגות',
                languages: 'אנגלית (שפת אם), קוריאנית (75%)',
                references: 'Olivia Wilson\nWardiere Inc. / CEO\n+123-456-7890\nhello@reallygreatsite.com'
            },
            en: {
                name: 'Jackson Anderson',
                title: 'Marketing Manager',
                phone: '+123-456-7890',
                email: 'hello@reallygreatsite.com',
                location: '123 Anywhere St., Any City',
                linkedin: '',
                summary: 'Marketing manager with a track record of brand campaigns, sales enablement, and digital growth across retail and international markets.',
                experience: '2020 - 2023 | Borcello International Co.\nMarketing Manager\n• Directed integrated campaigns across digital, retail, and partner channels.\n• Grew qualified pipeline and improved conversion on core product lines.\n• Built reporting cadences for leadership and regional sales teams.\n\n2019 - 2020 | Salford & Co.\nMarketing Manager\n• Owned go-to-market plans, creative briefs, and campaign calendars.\n• Partnered with sales on enablement kits, events, and launch messaging.',
                education: '2016 - 2019 | Borcello University\nMarketing Management\n\n2012 - 2016 | Rimberio University\nBusiness Administration',
                military: '',
                skills: 'Management Skills, Marketing Sales, Digital Marketing, Negotiation, Critical Thinking, Leadership',
                languages: 'English (native), Korean (75%)',
                references: 'Olivia Wilson\nWardiere Inc. / CEO\n+123-456-7890\nhello@reallygreatsite.com'
            }
        },
        navy: {
            title: 'נייבי תאגידי',
            titleHe: 'נייבי תאגידי',
            titleEn: 'Corporate Navy',
            subHe: 'תמר אברהם · מנהלת כספים',
            subEn: 'Tamar Abraham · Finance Manager',
            thumb: 'lay-navy',
            layout: 'navy',
            skin: '',
            accent: '#12192b',
            font: 'Montserrat',
            bg: 'bg-preview-white',
            field: 'sales',
            preferredLang: 'he',
            he: {
                name: 'תמר אברהם',
                title: 'מנהלת כספים',
                phone: '053-2203344',
                email: 'tamar.a@example.com',
                location: 'רמת גן',
                linkedin: 'linkedin.com/in/tamarabraham',
                summary: 'מנהלת כספים עם ניסיון בתקציב, בקרה ודוחות להנהלה בחברות צומחות.',
                experience: '2020 - נוכחי | Northwind Finance\nמנהלת כספים\n• בניית תקציב שנתי ומעקב שוטף מול יחידות העסק.\n• שיפור תזרים ודיווח ברור לדירקטוריון.\n\n2016 - 2020 | Apex Holdings\nחשבת\n• סגירות חודשיות, ספקים ומשכורות.',
                education: '2012 - 2016 | המכללה למנהל\nBA בכלכלה וחשבונאות',
                military: '2009 - 2011 | פקידת שלישות',
                skills: 'Excel מתקדם, תקציב, בקרה, SAP, דוחות הנהלה',
                languages: 'עברית (שפת אם), אנגלית (מקצועית)',
                references: ''
            },
            en: {
                name: 'Tamar Abraham',
                title: 'Finance Manager',
                phone: '053-2203344',
                email: 'tamar.a@example.com',
                location: 'Ramat Gan',
                linkedin: 'linkedin.com/in/tamarabraham',
                summary: 'Finance manager with experience in budgeting, controls, and leadership reporting in growing companies.',
                experience: '2020 - Present | Northwind Finance\nFinance Manager\n• Built the annual budget and tracked units against plan.\n• Improved cash flow and board reporting.\n\n2016 - 2020 | Apex Holdings\nAccountant\n• Month-end close, vendors, and payroll.',
                education: '2012 - 2016 | College of Management\nBA in Economics and Accounting',
                military: '2009 - 2011 | Personnel clerk',
                skills: 'Advanced Excel, budgeting, controls, SAP, board reporting',
                languages: 'Hebrew (native), English (professional)',
                references: ''
            }
        },
        azure: {
            title: 'כותרת תכלת',
            titleHe: 'כותרת תכלת',
            titleEn: 'Sky Header',
            subHe: 'ליאור חדד · מעצבת UX',
            subEn: 'Lior Hadad · UX Designer',
            thumb: 'lay-azure',
            layout: 'azure',
            skin: '',
            accent: '#3d5a6c',
            font: 'Heebo',
            bg: 'bg-preview-white',
            field: 'marketing',
            preferredLang: 'he',
            he: {
                name: 'ליאור חדד',
                title: 'מעצבת UX / UI',
                phone: '050-9988771',
                email: 'lior.hadad@example.com',
                location: 'תל אביב',
                linkedin: 'linkedin.com/in/liorhadad',
                summary: 'מעצבת מוצר עם דגש על מחקר, מערכות עיצוב ומסכים נקיים להגשה מקצועית.',
                experience: '2021 - נוכחי | Nimbus Studio\nמעצבת UX\n• עיצוב מסכי ליבה למוצר B2B והעלאת השלמת משימה ב-22%.\n• בניית Design System משותף עם הפיתוח.\n\n2018 - 2021 | Brightline\nמעצבת UI\n• דשבורדים, מצגות לקוח וספריית קומפוננטות.',
                education: '2014 - 2018 | שנקר\nB.Des עיצוב תקשורת חזותית',
                military: '2011 - 2013 | מעצבת גרפית ביחידה',
                skills: 'Figma, מחקר משתמשים, Design Systems, פרוטוטייפ, הנגשה',
                languages: 'עברית (שפת אם), אנגלית (גבוהה)',
                references: ''
            },
            en: {
                name: 'Lior Hadad',
                title: 'UX / UI Designer',
                phone: '050-9988771',
                email: 'lior.hadad@example.com',
                location: 'Tel Aviv',
                linkedin: 'linkedin.com/in/liorhadad',
                summary: 'Product designer focused on research, design systems, and clean screens for professional delivery.',
                experience: '2021 - Present | Nimbus Studio\nUX Designer\n• Designed core B2B flows and lifted task completion 22%.\n• Built a shared design system with engineering.\n\n2018 - 2021 | Brightline\nUI Designer\n• Dashboards, client decks, and a component library.',
                education: '2014 - 2018 | Shenkar\nB.Des Visual Communication',
                military: '2011 - 2013 | Unit graphic designer',
                skills: 'Figma, user research, design systems, prototyping, accessibility',
                languages: 'Hebrew (native), English (advanced)',
                references: ''
            }
        },
        mint: {
            title: 'טורקיז מודרני',
            titleHe: 'טורקיז מודרני',
            titleEn: 'Modern Teal',
            subHe: 'עומר חדד · הצלחת לקוח',
            subEn: 'Omer Hadad · Customer Success',
            thumb: 'lay-mint',
            layout: 'azure',
            skin: 'mint',
            accent: '#2f6f6a',
            font: 'Heebo',
            bg: 'bg-preview-mint',
            field: 'cs',
            preferredLang: 'he',
            he: {
                name: 'עומר חדד',
                title: 'מנהל הצלחת לקוח',
                phone: '054-2201188',
                email: 'omer.hadad@example.com',
                location: 'גבעתיים',
                linkedin: 'linkedin.com/in/omerhadad',
                summary: 'מנהל הצלחת לקוח עם דגש על שימור, הרחבת חשבון וטיפול בפניות מורכבות ב-SaaS.',
                experience: '2021 - נוכחי | Folia Cloud\nמנהל הצלחת לקוח\n• שימור 96% בתיק של 40 חשבונות והרחבת ARR ב-18%.\n• בניית תהליך קליטה ומעקב SLA מול התמיכה.\n\n2018 - 2021 | Helpdesk Pro\nנציג בכיר\n• טיפול בפניות מורכבות והדרכת נציגים חדשים.',
                education: '2014 - 2018 | האוניברסיטה הפתוחה\nBA בניהול',
                military: '2011 - 2014 | מש"ק שלישות',
                skills: 'הצלחת לקוח, CRM, SLA, תקשורת בינאישית, Zendesk',
                languages: 'עברית (שפת אם), אנגלית (שוטפת)',
                references: ''
            },
            en: {
                name: 'Omer Hadad',
                title: 'Customer Success Manager',
                phone: '054-2201188',
                email: 'omer.hadad@example.com',
                location: 'Givatayim',
                linkedin: 'linkedin.com/in/omerhadad',
                summary: 'Customer success manager focused on retention, account expansion, and complex SaaS support.',
                experience: '2021 - Present | Folia Cloud\nCustomer Success Manager\n• Held 96% retention across 40 accounts and grew ARR 18%.\n• Built onboarding and SLA tracking with support.\n\n2018 - 2021 | Helpdesk Pro\nSenior support specialist\n• Handled complex tickets and trained new agents.',
                education: '2014 - 2018 | Open University\nBA in Management',
                military: '2011 - 2014 | Personnel NCO',
                skills: 'Customer success, CRM, SLA, communication, Zendesk',
                languages: 'Hebrew (native), English (fluent)',
                references: ''
            }
        },
        ivory: {
            title: 'הנהלה',
            titleHe: 'הנהלה',
            titleEn: 'Executive',
            subHe: 'רועי נחום · מנהל תפעול',
            subEn: 'Roy Nahum · Operations Director',
            thumb: 'lay-ivory',
            layout: 'executive',
            skin: '',
            accent: '#3e342c',
            font: 'Frank Ruhl Libre',
            bg: 'bg-preview-cream',
            field: 'ops',
            preferredLang: 'he',
            he: {
                name: 'רועי נחום',
                title: 'מנהל תפעול',
                phone: '054-3311220',
                email: 'roy.nahum@example.com',
                location: 'פתח תקווה',
                linkedin: 'linkedin.com/in/roynahum',
                summary: 'מנהל תפעול עם ניסיון בשרשרת אספקה, SLA וצוותים בשטח. כותרת חמה וברורה להגשה להנהלה.',
                experience: '2019 - נוכחי | LogiPath\nמנהל תפעול\n• שיפור עמידה ב-SLA מ-82% ל-96% תוך שנה.\n• ניהול 40 עובדים בשלושה אתרים.\n\n2015 - 2019 | Retail Hub\nמנהל לוגיסטיקה\n• תכנון מלאי וספקים לחברה קמעונאית.',
                education: '2011 - 2015 | המכללה האקדמית ספיר\nBA בלוגיסטיקה',
                military: '2008 - 2011 | קצין לוגיסטיקה',
                skills: 'SLA, שרשרת אספקה, ניהול אתרים, Excel, תכנון כוח אדם',
                languages: 'עברית (שפת אם), אנגלית (מקצועית)',
                references: ''
            },
            en: {
                name: 'Roy Nahum',
                title: 'Operations Director',
                phone: '054-3311220',
                email: 'roy.nahum@example.com',
                location: 'Petah Tikva',
                linkedin: 'linkedin.com/in/roynahum',
                summary: 'Operations leader with supply-chain, SLA, and field-team experience. A warm executive header for leadership roles.',
                experience: '2019 - Present | LogiPath\nOperations Director\n• Lifted SLA from 82% to 96% within a year.\n• Led 40 people across three sites.\n\n2015 - 2019 | Retail Hub\nLogistics Manager\n• Inventory and vendor planning for a retail company.',
                education: '2011 - 2015 | Sapir Academic College\nBA in Logistics',
                military: '2008 - 2011 | Logistics officer',
                skills: 'SLA, supply chain, site management, Excel, workforce planning',
                languages: 'Hebrew (native), English (professional)',
                references: ''
            }
        },
        ink: {
            title: 'מינימלי ATS',
            titleHe: 'מינימלי ATS',
            titleEn: 'Minimal ATS',
            subHe: 'אלון כץ · מהנדס תוכנה',
            subEn: 'Alon Katz · Software Engineer',
            thumb: 'lay-ink',
            layout: 'minimal',
            skin: '',
            accent: '#1c1917',
            font: 'Inter',
            bg: 'bg-preview-white',
            field: 'tech',
            preferredLang: 'he',
            he: {
                name: 'אלון כץ',
                title: 'מהנדס תוכנה',
                phone: '050-1122334',
                email: 'alon.katz@example.com',
                location: 'תל אביב',
                linkedin: 'linkedin.com/in/alonkatz',
                summary: 'מהנדס תוכנה עם כתיבה נקייה, בדיקות וארכיטקטורה פשוטה. שחור-לבן לקריאות גבוהה במערכות גיוס.',
                experience: '2022 - נוכחי | Helix Systems\nמהנדס תוכנה\n• פיתוח שירותי Backend ב-Go ו-PostgreSQL.\n• הפחתת תקלות ייצור באמצעות בדיקות וניטור.\n\n2019 - 2022 | Pixel Forge\nמפתח\n• תחזוקת קוד קיים והעברת מודולים לשירותים.',
                education: '2015 - 2019 | אוניברסיטת בן-גוריון\nB.Sc הנדסת תוכנה',
                military: '2012 - 2015 | מפתח ביחידת מודיעין',
                skills: 'Go, PostgreSQL, Docker, Git, בדיקות',
                languages: 'עברית (שפת אם), אנגלית (טכנית)',
                references: ''
            },
            en: {
                name: 'Alon Katz',
                title: 'Software Engineer',
                phone: '050-1122334',
                email: 'alon.katz@example.com',
                location: 'Tel Aviv',
                linkedin: 'linkedin.com/in/alonkatz',
                summary: 'Software engineer focused on clean code, tests, and simple architecture. Black-and-white for high readability in hiring systems.',
                experience: '2022 - Present | Helix Systems\nSoftware Engineer\n• Built backend services in Go and PostgreSQL.\n• Reduced production incidents with tests and monitoring.\n\n2019 - 2022 | Pixel Forge\nDeveloper\n• Maintained legacy code and extracted services.',
                education: '2015 - 2019 | Ben-Gurion University\nB.Sc. Software Engineering',
                military: '2012 - 2015 | Intelligence-unit developer',
                skills: 'Go, PostgreSQL, Docker, Git, testing',
                languages: 'Hebrew (native), English (technical)',
                references: ''
            }
        },
        blush: {
            title: 'ורדרד עדין',
            titleHe: 'ורדרד עדין',
            titleEn: 'Soft Blush',
            subHe: 'שירה אלון · משאבי אנוש',
            subEn: 'Shira Alon · People Partner',
            thumb: 'lay-blush',
            layout: 'azure',
            skin: 'blush',
            accent: '#6b4a4e',
            font: 'Assistant',
            bg: 'bg-preview-pearl',
            field: 'marketing',
            preferredLang: 'he',
            he: {
                name: 'שירה אלון',
                title: 'HR Business Partner',
                phone: '052-6677889',
                email: 'shira.alon@example.com',
                location: 'רעננה',
                linkedin: 'linkedin.com/in/shiraalon',
                summary: 'שותפת משאבי אנוש עם דגש על גיוס איכותי, קליטה וליווי מנהלים.',
                experience: '2020 - נוכחי | Coral Labs\nHRBP\n• ליווי 80 עובדים בגיוס, קליטה ושיחות פיתוח.\n• בניית תהליך ראיונות אחיד עם מנהלים.\n\n2017 - 2020 | Talent Path\nרכזת גיוס\n• ניהול משפך מועמדים ושיפור זמן לגיוס.',
                education: '2013 - 2017 | המכללה האקדמית תל אביב-יפו\nBA במדעי ההתנהגות',
                military: '2010 - 2012 | מש"קית ת"ש',
                skills: 'גיוס, קליטה, ראיונות, Excel, ליווי מנהלים',
                languages: 'עברית (שפת אם), אנגלית (שוטפת)',
                references: ''
            },
            en: {
                name: 'Shira Alon',
                title: 'HR Business Partner',
                phone: '052-6677889',
                email: 'shira.alon@example.com',
                location: 'Ra\'anana',
                linkedin: 'linkedin.com/in/shiraalon',
                summary: 'People partner focused on quality hiring, onboarding, and manager support.',
                experience: '2020 - Present | Coral Labs\nHRBP\n• Supported 80 employees across hiring, onboarding, and development talks.\n• Built a consistent interview process with managers.\n\n2017 - 2020 | Talent Path\nRecruiting coordinator\n• Managed candidate pipelines and shortened time-to-hire.',
                education: '2013 - 2017 | Academic College of Tel Aviv-Yaffo\nBA in Behavioral Sciences',
                military: '2010 - 2012 | Welfare NCO',
                skills: 'Hiring, onboarding, interviews, Excel, manager coaching',
                languages: 'Hebrew (native), English (fluent)',
                references: ''
            }
        },
        espresso: {
            title: 'עורכי חם',
            titleHe: 'עורכי חם',
            titleEn: 'Warm Editorial',
            subHe: 'עמית לוי · מנהל מוצר',
            subEn: 'Amit Levy · Product Manager',
            thumb: 'lay-espresso',
            layout: 'charcoal',
            skin: 'espresso',
            accent: '#3e342c',
            font: 'Lato',
            bg: 'bg-preview-cream',
            field: 'tech',
            preferredLang: 'he',
            he: {
                name: 'עמית לוי',
                title: 'מנהל מוצר',
                phone: '052-4419088',
                email: 'amit.levy@example.com',
                location: 'תל אביב',
                linkedin: 'linkedin.com/in/amitlevy',
                summary: 'מנהל מוצר עם דגש על מסע לקוח, תעדוף ברור ושיתוף פעולה הדוק בין עיצוב, פיתוח ומכירות.',
                experience: '2021 - נוכחי | Northwind Apps\nמנהל מוצר\n• בניית מפת דרכים רבעונית והשקת פיצ\'רים שהעלו שימור ב-18%.\n• ניהול מחקר משתמשים והגדרת מדדי הצלחה מול ההנהלה.\n\n2018 - 2021 | Cedar Digital\nרכז מוצר\n• כתיבת אפיון, מעקב באגים ותיאום השקות עם שיווק.',
                education: '2014 - 2018 | אוניברסיטת תל אביב\nB.A. בניהול וכלכלה',
                military: '2011 - 2014 | קצין מבצעים',
                skills: 'Roadmap, מחקר משתמשים, Jira, SQL בסיסי, סדנאות אפיון',
                languages: 'עברית (שפת אם), אנגלית (שוטפת)',
                references: 'דנה שטרן\nLead Product / Northwind\n052-1112233\ndana@example.com'
            },
            en: {
                name: 'Amit Levy',
                title: 'Product Manager',
                phone: '052-4419088',
                email: 'amit.levy@example.com',
                location: 'Tel Aviv',
                linkedin: 'linkedin.com/in/amitlevy',
                summary: 'Product manager focused on customer journeys, clear prioritization, and tight collaboration across design, engineering, and sales.',
                experience: '2021 - Present | Northwind Apps\nProduct Manager\n• Built quarterly roadmaps and launched features that lifted retention 18%.\n• Ran user research and defined success metrics with leadership.\n\n2018 - 2021 | Cedar Digital\nProduct Coordinator\n• Wrote specs, tracked bugs, and coordinated launches with marketing.',
                education: '2014 - 2018 | Tel Aviv University\nB.A. in Management and Economics',
                military: '2011 - 2014 | Operations officer',
                skills: 'Roadmaps, user research, Jira, basic SQL, discovery workshops',
                languages: 'Hebrew (native), English (fluent)',
                references: 'Dana Stern\nLead Product / Northwind\n052-1112233\ndana@example.com'
            }
        },
        sage: {
            title: 'ירוק מקצועי',
            titleHe: 'ירוק מקצועי',
            titleEn: 'Professional Green',
            subHe: 'נועה כהן · מנהלת מכירות',
            subEn: 'Noa Cohen · Sales Manager',
            thumb: 'lay-sage',
            layout: 'charcoal',
            skin: 'sage',
            accent: '#4d5d52',
            font: 'Lato',
            bg: 'bg-preview-linen',
            field: 'sales',
            preferredLang: 'he',
            he: {
                name: 'נועה כהן',
                title: 'מנהלת מכירות ארצית',
                phone: '052-5550188',
                email: 'noa.cohen@example.com',
                location: 'הרצליה',
                linkedin: 'linkedin.com/in/noacohen',
                summary: 'מנהלת מכירות עם 8 שנות ניסיון בהובלת צוותים, בניית משפך מכירות והגדלת מחזור.',
                experience: '2021 - נוכחי | Verde Commerce\nמנהלת מכירות ארצית\n• הגדלת מחזור שנתי ב-35% תוך בניית צוות של 12 נציגים.\n• הטמעת CRM ומעקב KPI שבועי.\n\n2018 - 2021 | Shoreline B2B\nמנהלת לקוחות עסקיים\n• סגירת עסקאות מורכבות ושימור לקוחות אסטרטגיים.',
                education: '2014 - 2017 | המרכז הבינתחומי\nBA במנהל עסקים',
                military: '2011 - 2013 | קצינת הדרכה',
                skills: 'ניהול צוותים, CRM, משא ומתן, Excel, יעדי מכירות',
                languages: 'עברית (שפת אם), אנגלית (שוטפת)',
                references: ''
            },
            en: {
                name: 'Noa Cohen',
                title: 'National Sales Manager',
                phone: '052-5550188',
                email: 'noa.cohen@example.com',
                location: 'Herzliya',
                linkedin: 'linkedin.com/in/noacohen',
                summary: 'Sales manager with 8 years of experience leading teams, building pipelines, and growing revenue.',
                experience: '2021 - Present | Verde Commerce\nNational Sales Manager\n• Grew annual revenue 35% while building a team of 12.\n• Rolled out CRM and weekly KPI reviews.\n\n2018 - 2021 | Shoreline B2B\nAccount Manager\n• Closed complex deals and retained strategic clients.',
                education: '2014 - 2017 | Reichman University\nBA in Business Administration',
                military: '2011 - 2013 | Training officer',
                skills: 'Team leadership, CRM, negotiation, Excel, sales targets',
                languages: 'Hebrew (native), English (fluent)',
                references: ''
            }
        },
        slate: {
            title: 'הייטק דו-טורי',
            titleHe: 'הייטק דו-טורי',
            titleEn: 'Tech Two-Column',
            subHe: 'דניאל לוי · Full Stack',
            subEn: 'Daniel Levy · Full Stack',
            thumb: 'lay-slate',
            layout: 'charcoal',
            skin: 'slate',
            accent: '#3e4c58',
            font: 'IBM Plex Sans Hebrew',
            bg: 'bg-preview-white',
            field: 'tech',
            preferredLang: 'he',
            he: {
                name: 'דניאל לוי',
                title: 'מפתח Full Stack',
                phone: '054-2220199',
                email: 'daniel.levy@example.com',
                location: 'תל אביב',
                linkedin: 'linkedin.com/in/daniellevy',
                summary: 'מפתח עם ניסיון במוצרי SaaS, עבודה בצוות אג\'ייל ושיפור ביצועים בסביבת ייצור.',
                experience: '2022 - נוכחי | Cloudlane\nמפתח Full Stack\n• פיתוח פיצ\'רים מקצה לקצה ב-React ו-Node.\n• שיפור זמני טעינה ב-40% והוספת בדיקות אוטומטיות.\n\n2019 - 2022 | Stackyard\nמפתח Frontend\n• בניית ממשקים נגישים ועבודה מול עיצוב ו-QA.',
                education: '2016 - 2019 | הטכניון\nB.Sc מדעי המחשב',
                military: '2013 - 2016 | ממר"ם',
                skills: 'JavaScript, Git, APIs, SQL, עבודה בצוות אג\'ייל',
                languages: 'עברית (שפת אם), אנגלית (טכנית גבוהה)',
                references: ''
            },
            en: {
                name: 'Daniel Levy',
                title: 'Full Stack Developer',
                phone: '054-2220199',
                email: 'daniel.levy@example.com',
                location: 'Tel Aviv',
                linkedin: 'linkedin.com/in/daniellevy',
                summary: 'Developer with SaaS product experience, agile teamwork, and production performance work.',
                experience: '2022 - Present | Cloudlane\nFull Stack Developer\n• Shipped end-to-end features in React and Node.\n• Cut load times 40% and added automated tests.\n\n2019 - 2022 | Stackyard\nFrontend Developer\n• Built accessible interfaces with design and QA.',
                education: '2016 - 2019 | Technion\nB.Sc. Computer Science',
                military: '2013 - 2016 | Mamram',
                skills: 'JavaScript, Git, APIs, SQL, agile teamwork',
                languages: 'Hebrew (native), English (professional)',
                references: ''
            }
        },
        wine: {
            title: 'בורדו שיווקי',
            titleHe: 'בורדו שיווקי',
            titleEn: 'Burgundy',
            subHe: 'מאיה ברק · שיווק דיגיטלי',
            subEn: 'Maya Barak · Digital Marketing',
            thumb: 'lay-wine',
            layout: 'charcoal',
            skin: 'wine',
            accent: '#5a3640',
            font: 'Heebo',
            bg: 'bg-preview-cream',
            field: 'marketing',
            preferredLang: 'he',
            he: {
                name: 'מאיה ברק',
                title: 'מנהלת שיווק דיגיטלי',
                phone: '050-7770144',
                email: 'maya.barak@example.com',
                location: 'חיפה',
                linkedin: 'linkedin.com/in/mayabarak',
                summary: 'מנהלת שיווק דיגיטלי עם דגש על לידים איכותיים, תוכן ואופטימיזציית תקציב.',
                experience: '2020 - נוכחי | Maroon Media\nמנהלת שיווק דיגיטלי\n• ניהול קמפיינים ב-Google ו-Meta והגדלת לידים ב-50%.\n• בניית מסרים למותג ותוכן לרשתות.\n\n2017 - 2020 | Pulse Agency\nרכזת דיגיטל\n• ניתוח GA ואופטימיזציה שבועית של קריאייטיב.',
                education: '2013 - 2016 | אוניברסיטת חיפה\nBA בתקשורת',
                military: '2010 - 2012 | דוברת יחידה',
                skills: 'Google Ads, Meta Ads, תוכן, GA4, קריאייטיב',
                languages: 'עברית (שפת אם), אנגלית (גבוהה)',
                references: ''
            },
            en: {
                name: 'Maya Barak',
                title: 'Digital Marketing Manager',
                phone: '050-7770144',
                email: 'maya.barak@example.com',
                location: 'Haifa',
                linkedin: 'linkedin.com/in/mayabarak',
                summary: 'Digital marketing manager focused on quality leads, content, and paid-media optimization.',
                experience: '2020 - Present | Maroon Media\nDigital Marketing Manager\n• Ran Google and Meta campaigns and grew leads 50%.\n• Built brand messaging and social content.\n\n2017 - 2020 | Pulse Agency\nDigital Coordinator\n• Analyzed GA and optimized creative weekly.',
                education: '2013 - 2016 | University of Haifa\nBA in Communications',
                military: '2010 - 2012 | Unit spokesperson',
                skills: 'Google Ads, Meta Ads, content, GA4, creative',
                languages: 'Hebrew (native), English (advanced)',
                references: ''
            }
        },
        forest: {
            title: 'ייעוץ יער',
            titleHe: 'ייעוץ יער',
            titleEn: 'Forest Consulting',
            subHe: 'יונתן מזרחי · יועץ ארגוני',
            subEn: 'Yonatan Mizrahi · Org. Consultant',
            thumb: 'lay-forest',
            layout: 'charcoal',
            skin: 'forest',
            accent: '#31443b',
            font: 'Lato',
            bg: 'bg-preview-linen',
            field: 'sales',
            preferredLang: 'he',
            he: {
                name: 'יונתן מזרחי',
                title: 'יועץ ארגוני',
                phone: '054-8801122',
                email: 'yonatan.m@example.com',
                location: 'ירושלים',
                linkedin: 'linkedin.com/in/yonatanm',
                summary: 'יועץ ארגוני המלווה הנהלות בתהליכי שינוי, מבנה צוותים ותרבות עבודה ברורה.',
                experience: '2019 - נוכחי | Mizrahi Consulting\nיועץ ארגוני עצמאי\n• ליווי 14 ארגונים בתהליכי שינוי ומדידת אפקטיביות.\n• בניית סדנאות הנהלה ותוכניות פיתוח מנהלים.\n\n2015 - 2019 | Cedar Tech\nHR Business Partner\n• גיוס הנהלה וליווי מנהלים בצוותי הייטק.',
                education: '2011 - 2015 | האוניברסיטה העברית\nM.A. בפסיכולוגיה ארגונית',
                military: '2008 - 2011 | קצין משא"ן',
                skills: 'ליווי הנהלה, סדנאות, אבחון ארגוני, גיוס, מדידה',
                languages: 'עברית (שפת אם), אנגלית (גבוהה)',
                references: ''
            },
            en: {
                name: 'Yonatan Mizrahi',
                title: 'Organizational Consultant',
                phone: '054-8801122',
                email: 'yonatan.m@example.com',
                location: 'Jerusalem',
                linkedin: 'linkedin.com/in/yonatanm',
                summary: 'Consultant supporting leadership teams through change, team design, and a clearer working culture.',
                experience: '2019 - Present | Mizrahi Consulting\nIndependent consultant\n• Advised 14 organizations on change programs and effectiveness measures.\n• Designed leadership workshops and manager development plans.\n\n2015 - 2019 | Cedar Tech\nHR Business Partner\n• Hired executives and coached managers in tech teams.',
                education: '2011 - 2015 | Hebrew University\nM.A. in Organizational Psychology',
                military: '2008 - 2011 | Personnel officer',
                skills: 'Executive coaching, workshops, org diagnosis, hiring, measurement',
                languages: 'Hebrew (native), English (advanced)',
                references: ''
            }
        },
        terracotta: {
            title: 'טרקוטה יצירתי',
            titleHe: 'טרקוטה יצירתי',
            titleEn: 'Creative Terracotta',
            subHe: 'נועם אורן · מעצב גרפי',
            subEn: 'Noam Oren · Graphic Designer',
            thumb: 'lay-terracotta',
            layout: 'azure',
            skin: 'terracotta',
            accent: '#9a5b42',
            font: 'Assistant',
            bg: 'bg-preview-linen',
            field: 'marketing',
            preferredLang: 'he',
            he: {
                name: 'נועם אורן',
                title: 'מעצב גרפי',
                phone: '050-3342211',
                email: 'noam.oren@example.com',
                location: 'יפו',
                linkedin: 'linkedin.com/in/noamoren',
                summary: 'מעצב גרפי למותגים, אריזות ודיגיטל. פלטה חמה בסגנון Canva לקורות חיים יצירתיים שעדיין נשארים קריאים.',
                experience: '2020 - נוכחי | Clay & Co.\nמעצב גרפי בכיר\n• זהות מותג ל-12 לקוחות והובלת קמפיינים חזותיים.\n• עיצוב אריזה, מצגות ונכסים לרשתות.\n\n2017 - 2020 | Studio Arava\nמעצב\n• לוגו, דפוס ועימוד לקטלוגים.',
                education: '2013 - 2017 | בצלאל\nB.Des תקשורת חזותית',
                military: '2010 - 2012 | מעצב ביחידה',
                skills: 'Illustrator, Photoshop, InDesign, זהות מותג, דפוס',
                languages: 'עברית (שפת אם), אנגלית (גבוהה)',
                references: ''
            },
            en: {
                name: 'Noam Oren',
                title: 'Graphic Designer',
                phone: '050-3342211',
                email: 'noam.oren@example.com',
                location: 'Jaffa',
                linkedin: 'linkedin.com/in/noamoren',
                summary: 'Graphic designer for brands, packaging, and digital. A warm Canva-style palette that stays readable.',
                experience: '2020 - Present | Clay & Co.\nSenior graphic designer\n• Brand identity for 12 clients and visual campaign lead.\n• Packaging, decks, and social assets.\n\n2017 - 2020 | Studio Arava\nDesigner\n• Logos, print, and catalog layout.',
                education: '2013 - 2017 | Bezalel\nB.Des Visual Communication',
                military: '2010 - 2012 | Unit designer',
                skills: 'Illustrator, Photoshop, InDesign, brand identity, print',
                languages: 'Hebrew (native), English (advanced)',
                references: ''
            }
        },
        cream: {
            title: 'שמנת אלגנטית',
            titleHe: 'שמנת אלגנטית',
            titleEn: 'Elegant Cream',
            subHe: 'דנה לוי · שירות לקוחות',
            subEn: 'Dana Levi · Customer Service',
            thumb: 'lay-cream',
            layout: 'azure',
            skin: 'cream',
            accent: '#7a6a55',
            font: 'Frank Ruhl Libre',
            bg: 'bg-preview-cream',
            field: 'cs',
            preferredLang: 'he',
            he: {
                name: 'דנה לוי',
                title: 'מנהלת שירות לקוחות',
                phone: '053-7788990',
                email: 'dana.levi@example.com',
                location: 'נס ציונה',
                linkedin: 'linkedin.com/in/danalevi',
                summary: 'מנהלת שירות עם דגש על שביעות רצון, זמני מענה ותיעוד תהליכים בצוות גדול.',
                experience: '2020 - נוכחי | Softline Retail\nמנהלת שירות לקוחות\n• שיפור ציון שביעות רצון מ-4.1 ל-4.7 וקיצור זמן מענה ב-30%.\n• תיעוד תהליכים והדרכת 15 נציגים.\n\n2017 - 2020 | Callora\nנציגת שירות\n• טיפול בפניות מורכבות וזיהוי דפוסי תקלות למוצר.',
                education: '2013 - 2017 | המכללה האקדמית אשקלון\nBA במנהל עסקים',
                military: '2010 - 2012 | פקידת מבצעים',
                skills: 'שירות לקוחות, CRM, SLA, תקשורת בינאישית, הדרכה',
                languages: 'עברית (שפת אם), אנגלית (שוטפת)',
                references: ''
            },
            en: {
                name: 'Dana Levi',
                title: 'Customer Service Manager',
                phone: '053-7788990',
                email: 'dana.levi@example.com',
                location: 'Ness Ziona',
                linkedin: 'linkedin.com/in/danalevi',
                summary: 'Service manager focused on satisfaction scores, response times, and documented processes in a large team.',
                experience: '2020 - Present | Softline Retail\nCustomer Service Manager\n• Lifted CSAT from 4.1 to 4.7 and cut response time 30%.\n• Documented processes and trained 15 agents.\n\n2017 - 2020 | Callora\nService specialist\n• Handled complex cases and flagged product issue patterns.',
                education: '2013 - 2017 | Ashkelon Academic College\nBA in Business Administration',
                military: '2010 - 2012 | Operations clerk',
                skills: 'Customer service, CRM, SLA, communication, training',
                languages: 'Hebrew (native), English (fluent)',
                references: ''
            }
        },
        sand: {
            title: 'סרגל חם',
            titleHe: 'סרגל חם',
            titleEn: 'Warm Sidebar',
            subHe: 'הילה פרץ · אדריכלית פנים',
            subEn: 'Hila Peretz · Interior Architect',
            thumb: 'lay-sand',
            layout: 'sidebar',
            skin: '',
            accent: '#6b5344',
            font: 'Heebo',
            bg: 'bg-preview-linen',
            field: 'marketing',
            preferredLang: 'he',
            he: {
                name: 'הילה פרץ',
                title: 'אדריכלית פנים',
                phone: '052-9090880',
                email: 'hila.peretz@example.com',
                location: 'יפו',
                linkedin: 'linkedin.com/in/hilaperetz',
                summary: 'אדריכלית פנים לפרויקטים למגורים ומסחר, עם דגש על חומר, אור ותכנון פרקטי.',
                experience: '2018 - נוכחי | סטודיו פרץ\nאדריכלית פנים עצמאית\n• תכנון 30 דירות וחללי מסחר, מלווי לקוח ועד פיקוח.\n• ניהול ספקים, תקציב ולוחות זמנים.\n\n2014 - 2018 | משרד אדריכלים יפו\nאדריכלית במשרד\n• שרטוטים, הדמיות וליווי ביצוע.',
                education: '2010 - 2014 | הטכניון\nB.Arch אדריכלות',
                military: '2007 - 2009 | מש"קית חינוך',
                skills: 'AutoCAD, SketchUp, פיקוח, תקציב, חומרים',
                languages: 'עברית (שפת אם), אנגלית (גבוהה)',
                references: ''
            },
            en: {
                name: 'Hila Peretz',
                title: 'Interior Architect',
                phone: '052-9090880',
                email: 'hila.peretz@example.com',
                location: 'Jaffa',
                linkedin: 'linkedin.com/in/hilaperetz',
                summary: 'Interior architect for residential and commercial projects, with a focus on material, light, and practical planning.',
                experience: '2018 - Present | Peretz Studio\nIndependent interior architect\n• Designed 30 homes and commercial interiors from brief to site.\n• Managed vendors, budgets, and schedules.\n\n2014 - 2018 | Jaffa Architecture Office\nStudio architect\n• Drawings, renders, and construction follow-up.',
                education: '2010 - 2014 | Technion\nB.Arch Architecture',
                military: '2007 - 2009 | Education NCO',
                skills: 'AutoCAD, SketchUp, site supervision, budgets, materials',
                languages: 'Hebrew (native), English (advanced)',
                references: ''
            }
        },
        pearl: {
            title: 'מודרני נקי',
            titleHe: 'מודרני נקי',
            titleEn: 'Clean Modern',
            subHe: 'מיכל דהן · מנהלת תוכן',
            subEn: 'Michal Dahan · Content Lead',
            thumb: 'lay-pearl',
            layout: 'modern',
            skin: '',
            accent: '#3e4c58',
            font: 'Assistant',
            bg: 'bg-preview-pearl',
            field: 'marketing',
            preferredLang: 'he',
            he: {
                name: 'מיכל דהן',
                title: 'מנהלת תוכן',
                phone: '053-4455667',
                email: 'michal.dahan@example.com',
                location: 'חולון',
                linkedin: 'linkedin.com/in/michaldahan',
                summary: 'מנהלת תוכן עם ניסיון במסרים למותג, אתרים ורשתות.',
                experience: '2021 - נוכחי | Pearl Media\nמנהלת תוכן\n• בניית לוח תוכן חודשי והעלאת מעורבות ב-40%.\n• עריכת אתר ודפי נחיתה עם צוות עיצוב.\n\n2018 - 2021 | Ink & Co.\nכותבת תוכן\n• מאמרים, ניוזלטר ומסרים למודעות.',
                education: '2014 - 2018 | אוניברסיטת בן-גוריון\nBA בספרות ותקשורת',
                military: '2011 - 2013 | כתבת ביחידה',
                skills: 'עריכה, SEO בסיסי, ניוזלטר, בריפים, Notion',
                languages: 'עברית (שפת אם), אנגלית (גבוהה)',
                references: ''
            },
            en: {
                name: 'Michal Dahan',
                title: 'Content Lead',
                phone: '053-4455667',
                email: 'michal.dahan@example.com',
                location: 'Holon',
                linkedin: 'linkedin.com/in/michaldahan',
                summary: 'Content lead with brand messaging, web, and social experience.',
                experience: '2021 - Present | Pearl Media\nContent Lead\n• Built a monthly content calendar and lifted engagement 40%.\n• Edited the site and landing pages with design.\n\n2018 - 2021 | Ink & Co.\nContent writer\n• Articles, newsletters, and ad copy.',
                education: '2014 - 2018 | Ben-Gurion University\nBA in Literature and Communications',
                military: '2011 - 2013 | Unit writer',
                skills: 'Editing, basic SEO, newsletters, briefs, Notion',
                languages: 'Hebrew (native), English (advanced)',
                references: ''
            }
        },
        swiss: {
            title: 'שוויצרי',
            titleHe: 'שוויצרי',
            titleEn: 'Swiss Modern',
            subHe: 'גיא בר · מעצב מוצר',
            subEn: 'Guy Barr · Product Designer',
            thumb: 'lay-swiss',
            layout: 'modern',
            skin: '',
            accent: '#1c1917',
            font: 'Inter',
            bg: 'bg-preview-white',
            field: 'tech',
            preferredLang: 'he',
            he: {
                name: 'גיא בר',
                title: 'מעצב מוצר',
                phone: '054-1199002',
                email: 'guy.barr@example.com',
                location: 'תל אביב',
                linkedin: 'linkedin.com/in/guybarr',
                summary: 'מעצב מוצר עם גישה שוויצרית: היררכיה ברורה, ריווח נדיב ומסכים שעובדים בעברית ובאנגלית.',
                experience: '2021 - נוכחי | Grid & Form\nמעצב מוצר\n• עיצוב מערכת רכיבים למוצר B2B והפחתת זמן מסירה לעיצוב.\n• מחקר שימושיות והטמעה עם פיתוח.\n\n2018 - 2021 | Mono Studio\nמעצב UI\n• אתרים, אפליקציות ומצגות ללקוחות הייטק.',
                education: '2014 - 2018 | HIT\nB.Des עיצוב מדיה',
                military: '2011 - 2014 | מעצב גרפי',
                skills: 'Figma, מחקר, מערכות עיצוב, פרוטוטייפ, הנגשה',
                languages: 'עברית (שפת אם), אנגלית (שוטפת)',
                references: ''
            },
            en: {
                name: 'Guy Barr',
                title: 'Product Designer',
                phone: '054-1199002',
                email: 'guy.barr@example.com',
                location: 'Tel Aviv',
                linkedin: 'linkedin.com/in/guybarr',
                summary: 'Product designer with a Swiss approach: clear hierarchy, generous spacing, and screens that work in Hebrew and English.',
                experience: '2021 - Present | Grid & Form\nProduct designer\n• Designed a B2B component system and shortened design handoff.\n• Ran usability research with engineering.\n\n2018 - 2021 | Mono Studio\nUI designer\n• Sites, apps, and decks for tech clients.',
                education: '2014 - 2018 | HIT\nB.Des Media Design',
                military: '2011 - 2014 | Graphic designer',
                skills: 'Figma, research, design systems, prototyping, accessibility',
                languages: 'Hebrew (native), English (fluent)',
                references: ''
            }
        },
        compact: {
            title: 'עמוד אחד',
            titleHe: 'עמוד אחד',
            titleEn: 'One Page',
            subHe: 'אייל גולן · אנליסט',
            subEn: 'Eyal Golan · Analyst',
            thumb: 'lay-compact',
            layout: 'compact',
            skin: '',
            accent: '#4c4c4c',
            font: 'Rubik',
            bg: 'bg-preview-slate',
            field: 'tech',
            preferredLang: 'he',
            he: {
                name: 'אייל גולן',
                title: 'אנליסט נתונים',
                phone: '054-7766554',
                email: 'eyal.golan@example.com',
                location: 'באר שבע',
                linkedin: 'linkedin.com/in/eyalgolan',
                summary: 'אנליסט עם דגש על דוחות ברורים, SQL ודשבורדים להנהלה. פריסה צפופה שנשארת בעמוד אחד.',
                experience: '2021 - נוכחי | Datafold\nאנליסט\n• בניית דשבורדים ב-Looker וחיסכון של 8 שעות דיווח בשבוע.\n• ניתוח משפך מכירות מול צוות ה-CRO.\n\n2018 - 2021 | Insight Lab\nאנליסט זוטר\n• שאילתות SQL וניקוי נתונים.',
                education: '2014 - 2018 | אוניברסיטת בן-גוריון\nB.Sc סטטיסטיקה',
                military: '2011 - 2014 | מש"ק מודיעין',
                skills: 'SQL, Looker, Excel, Python בסיסי, ויזואליזציה',
                languages: 'עברית (שפת אם), אנגלית (מקצועית)',
                references: ''
            },
            en: {
                name: 'Eyal Golan',
                title: 'Data Analyst',
                phone: '054-7766554',
                email: 'eyal.golan@example.com',
                location: 'Be\'er Sheva',
                linkedin: 'linkedin.com/in/eyalgolan',
                summary: 'Analyst focused on clear reports, SQL, and leadership dashboards. A dense layout that stays on one page.',
                experience: '2021 - Present | Datafold\nAnalyst\n• Built Looker dashboards and saved 8 reporting hours a week.\n• Analyzed the sales funnel with the CRO team.\n\n2018 - 2021 | Insight Lab\nJunior analyst\n• SQL queries and data cleanup.',
                education: '2014 - 2018 | Ben-Gurion University\nB.Sc. Statistics',
                military: '2011 - 2014 | Intelligence NCO',
                skills: 'SQL, Looker, Excel, basic Python, visualization',
                languages: 'Hebrew (native), English (professional)',
                references: ''
            }
        },
        intern: {
            title: 'סטודנט / מתמחה',
            titleHe: 'סטודנט / מתמחה',
            titleEn: 'Student Intern',
            subHe: 'מאיה רוזן · סטודנטית מדמח',
            subEn: 'Maya Rosen · CS Student',
            thumb: 'lay-intern',
            layout: 'compact',
            skin: '',
            accent: '#3e4c58',
            font: 'Rubik',
            bg: 'bg-preview-slate',
            field: 'student',
            preferredLang: 'he',
            he: {
                name: 'מאיה רוזן',
                title: 'סטודנטית למדעי המחשב · מחפשת התמחות',
                phone: '050-6677881',
                email: 'maya.rosen@example.com',
                location: 'ראשון לציון',
                linkedin: 'linkedin.com/in/mayarosen',
                summary: 'סטודנטית שנה ג\' עם פרויקטי קורס, האקאתון וניסיון ראשון בפיתוח במשרה חלקית.',
                experience: '2024 - נוכחי | Campus Labs\nמתמחה פיתוח (חלקי)\n• בניית דפי פנימיים ב-React ותיקוני באגים בליווי מנטור.\n• כתיבת בדיקות בסיסיות ותיעוד.\n\n2023 | האקאתון Technion\nמשתתפת\n• אב-טיפוס לכלי סיכום שיעורים ב-48 שעות.',
                education: '2022 - נוכחי | אוניברסיטת תל אביב\nB.Sc מדעי המחשב (שנה ג\')',
                military: '2019 - 2021 | מש"קית תקשוב',
                skills: 'JavaScript, Python, Git, HTML/CSS, עבודת צוות',
                languages: 'עברית (שפת אם), אנגלית (גבוהה)',
                references: ''
            },
            en: {
                name: 'Maya Rosen',
                title: 'Computer Science student · Seeking internship',
                phone: '050-6677881',
                email: 'maya.rosen@example.com',
                location: 'Rishon LeZion',
                linkedin: 'linkedin.com/in/mayarosen',
                summary: 'Third-year student with course projects, a hackathon, and first part-time development experience.',
                experience: '2024 - Present | Campus Labs\nSoftware intern (part-time)\n• Built internal React pages and fixed bugs with a mentor.\n• Wrote basic tests and documentation.\n\n2023 | Technion Hackathon\nParticipant\n• Prototype for a lecture-summary tool in 48 hours.',
                education: '2022 - Present | Tel Aviv University\nB.Sc. Computer Science (year 3)',
                military: '2019 - 2021 | Communications NCO',
                skills: 'JavaScript, Python, Git, HTML/CSS, teamwork',
                languages: 'Hebrew (native), English (advanced)',
                references: ''
            }
        },
        academic: {
            title: 'אקדמי',
            titleHe: 'אקדמי',
            titleEn: 'Academic CV',
            subHe: 'ד"ר עדי נחום · חוקרת',
            subEn: 'Dr. Adi Nahum · Researcher',
            thumb: 'lay-academic',
            layout: 'classic',
            skin: '',
            accent: '#3e342c',
            font: 'Frank Ruhl Libre',
            bg: 'bg-preview-cream',
            field: 'edu',
            preferredLang: 'he',
            he: {
                name: 'ד"ר עדי נחום',
                title: 'חוקרת · מדעי החברה',
                phone: '052-3304411',
                email: 'adi.nahum@example.com',
                location: 'ירושלים',
                linkedin: 'linkedin.com/in/adinahum',
                summary: 'חוקרת עם ניסיון בהוראה אקדמית, פרסומים שפיטים וניהול מענק מחקר.',
                experience: '2021 - נוכחי | האוניברסיטה העברית\nעמיתת מחקר והוראה\n• הוראת שני קורסי מבוא והנחיית סמינר תואר ראשון.\n• פרסום שני מאמרים שפיטים וניהול מענק פנימי.\n\n2018 - 2021 | אוניברסיטת בן-גוריון\nדוקטורנטית\n• מחקר כמותי, איסוף נתונים וכתיבה אקדמית.',
                education: '2018 - 2021 | אוניברסיטת בן-גוריון\nPh.D. מדעי החברה\n2015 - 2018 | האוניברסיטה העברית\nM.A. סוציולוגיה',
                military: '2010 - 2012 | קצינת הדרכה',
                skills: 'הוראה, מחקר כמותי, כתיבה אקדמית, SPSS, הנחיית סטודנטים',
                languages: 'עברית (שפת אם), אנגלית אקדמית',
                references: ''
            },
            en: {
                name: 'Dr. Adi Nahum',
                title: 'Researcher · Social Sciences',
                phone: '052-3304411',
                email: 'adi.nahum@example.com',
                location: 'Jerusalem',
                linkedin: 'linkedin.com/in/adinahum',
                summary: 'Researcher with academic teaching, peer-reviewed publications, and grant management.',
                experience: '2021 - Present | Hebrew University\nResearch and teaching fellow\n• Taught two intro courses and advised an undergraduate seminar.\n• Published two peer-reviewed papers and managed an internal grant.\n\n2018 - 2021 | Ben-Gurion University\nPh.D. candidate\n• Quantitative research, data collection, and academic writing.',
                education: '2018 - 2021 | Ben-Gurion University\nPh.D. Social Sciences\n2015 - 2018 | Hebrew University\nM.A. Sociology',
                military: '2010 - 2012 | Training officer',
                skills: 'Teaching, quantitative research, academic writing, SPSS, student advising',
                languages: 'Hebrew (native), academic English',
                references: ''
            }
        },
        split: {
            title: 'מפוצל קלאסי',
            titleHe: 'מפוצל קלאסי',
            titleEn: 'Split Serif',
            subHe: 'קרן אזולאי · עורכת דין',
            subEn: 'Keren Azulay · Attorney',
            thumb: 'lay-split-sand',
            layout: 'split',
            skin: '',
            accent: '#3e342c',
            font: 'Frank Ruhl Libre',
            bg: 'bg-preview-cream',
            field: 'sales',
            preferredLang: 'he',
            he: {
                name: 'קרן אזולאי',
                title: 'עורכת דין מסחרי',
                phone: '050-3344556',
                email: 'keren.azulay@example.com',
                location: 'תל אביב',
                linkedin: 'linkedin.com/in/kerenazulay',
                summary: 'עורכת דין מסחרי עם ניסיון בחוזים, ליווי עסקאות ומשא ומתן.',
                experience: '2018 - נוכחי | משרד אזולאי ושות\'\nעורכת דין\n• ליווי עסקאות רכישה וניסוח הסכמים מסחריים.\n• משא ומתן מול ספקים ולקוחות אסטרטגיים.\n\n2015 - 2018 | משרד גולן\nמתמחה ועורכת דין זוטרה\n• מחקר משפטי וליווי התדיינויות.',
                education: '2011 - 2015 | אוניברסיטת תל אביב\nLL.B משפטים',
                military: '2008 - 2010 | קצינת שלישות',
                skills: 'חוזים, עסקאות, מחקר משפטי, משא ומתן, עברית משפטית',
                languages: 'עברית (שפת אם), אנגלית משפטית',
                references: ''
            },
            en: {
                name: 'Keren Azulay',
                title: 'Commercial Attorney',
                phone: '050-3344556',
                email: 'keren.azulay@example.com',
                location: 'Tel Aviv',
                linkedin: 'linkedin.com/in/kerenazulay',
                summary: 'Commercial attorney with experience in contracts, deal support, and negotiation.',
                experience: '2018 - Present | Azulay & Co.\nAssociate\n• Supported acquisitions and drafted commercial agreements.\n• Negotiated with vendors and strategic clients.\n\n2015 - 2018 | Golan Law\nIntern and junior attorney\n• Legal research and litigation support.',
                education: '2011 - 2015 | Tel Aviv University\nLL.B. Law',
                military: '2008 - 2010 | Personnel officer',
                skills: 'Contracts, deals, legal research, negotiation, legal Hebrew',
                languages: 'Hebrew (native), legal English',
                references: ''
            }
        },
        petra: {
            title: 'ציר־זמן נייבי',
            titleHe: 'ציר־זמן נייבי',
            titleEn: 'Navy Timeline',
            subHe: 'קיירי פטרקיס · רואה חשבון',
            subEn: 'Kyrie Petrakis · Accountant Expert',
            thumb: 'lay-petra',
            layout: 'navy',
            skin: '',
            accent: '#12192b',
            font: 'Montserrat',
            bg: 'bg-preview-white',
            field: 'finance',
            preferredLang: 'en',
            he: {
                name: 'קיירי פטרקיס',
                title: 'רואה חשבון בכיר',
                phone: '052-4410190',
                email: 'kyrie.petrakis@example.com',
                location: 'תל אביב',
                linkedin: 'kyriepetrakis.com',
                summary: 'רואה חשבון עם ניסיון בדוחות כספיים, ציות מס והערכת סיכונים. פריסה דו־טורית עם תמונה עגולה וציר זמן — הסגנון הנפוץ ביותר בתבניות Canva.',
                experience: '2020 - 2022 | Northline Audit\nרואה חשבון בכיר\n• הכנת דוחות כספיים וליווי סגירות רבעוניות ללקוחות בינוניים.\n• שיפור תהליכי בקרה והפחתת ממצאי ביקורת.\n\n2017 - 2020 | Harbor Tax\nחשב\n• טיפול בדיווחי מס, התאמות בנקים וליווי לקוחות בעונת השומה.',
                education: '2013 - 2017 | המכללה למנהל\nBA בחשבונאות וכלכלה\n2018 | רישיון רואה חשבון',
                military: '2010 - 2013 | פקיד כספים',
                skills: 'דוחות כספיים, ציות מס, הערכת סיכונים, Excel, SAP',
                languages: 'עברית (שפת אם), אנגלית (Excellent)',
                references: ''
            },
            en: {
                name: 'Kyrie Petrakis',
                title: 'Accountant Expert',
                phone: '+123-456-7890',
                email: 'hello@reallygreatsite.com',
                location: '123 Anywhere St., Any City',
                linkedin: 'www.reallygreatsite.com',
                summary: 'Detail-oriented accountant with a record of clean financial reporting, tax compliance, and practical risk review. A high-contrast two-column layout with a circular photo and timeline markers.',
                experience: '2020 - 2022 | Northline Audit\nSenior Accountant\n• Prepared financial statements and supported quarterly close for mid-size clients.\n• Tightened internal controls and reduced audit findings.\n\n2017 - 2020 | Harbor Tax\nStaff Accountant\n• Filed tax returns, reconciled bank accounts, and supported clients through filing season.',
                education: '2013 - 2017 | Borcello University\nB.A. Accounting and Finance\n2018 | CPA license',
                military: '',
                skills: 'Financial Reporting, Tax Compliance, Risk Assessment, Excel, SAP',
                languages: 'English (Excellent), Greek (Good)',
                references: ''
            }
        },
        midnight: {
            title: 'חצות ניהולי',
            titleHe: 'חצות ניהולי',
            titleEn: 'Midnight Executive',
            subHe: 'אלכס מור · מנכ"ל תפעול',
            subEn: 'Alex Moore · COO',
            thumb: 'lay-midnight',
            layout: 'navy',
            skin: 'midnight',
            accent: '#12192b',
            font: 'Montserrat',
            bg: 'bg-preview-white',
            field: 'ops',
            preferredLang: 'en',
            he: {
                name: 'אלכס מור',
                title: 'סמנכ"ל תפעול',
                phone: '054-2203344',
                email: 'alex.moore@example.com',
                location: 'הרצליה',
                linkedin: 'linkedin.com/in/alexmoore',
                summary: 'מנהל תפעול עם ניסיון בהובלת צמיחה, ייעול תהליכים ודיווח להנהלה. סרגל כהה כמעט שחור להגשה לתפקידי C-level.',
                experience: '2019 - נוכחי | Apex Operations\nסמנכ"ל תפעול\n• בניית תוכנית תפעול שנתית והורדת עלות יחידה ב-14%.\n• ניהול 90 עובדים בשלושה אתרים.\n\n2015 - 2019 | Harbor Group\nמנהל תפעול\n• שיפור SLA, מלאי וקשרי ספקים.',
                education: '2011 - 2015 | אוניברסיטת תל אביב\nMBA\n2007 - 2011 | הטכניון\nB.Sc הנדסת תעשייה',
                military: '2004 - 2007 | קצין לוגיסטיקה',
                skills: 'P&L, KPI, שרשרת אספקה, ניהול אתרים, דיווח דירקטוריון',
                languages: 'עברית (שפת אם), אנגלית (שוטפת)',
                references: ''
            },
            en: {
                name: 'Alex Moore',
                title: 'Chief Operating Officer',
                phone: '054-2203344',
                email: 'alex.moore@example.com',
                location: 'Herzliya',
                linkedin: 'linkedin.com/in/alexmoore',
                summary: 'Operations executive focused on growth, process discipline, and board-ready reporting. A near-black sidebar for C-level applications.',
                experience: '2019 - Present | Apex Operations\nChief Operating Officer\n• Built the annual operating plan and cut unit cost 14%.\n• Led 90 people across three sites.\n\n2015 - 2019 | Harbor Group\nOperations Director\n• Improved SLA, inventory, and vendor relationships.',
                education: '2011 - 2015 | Tel Aviv University\nMBA\n2007 - 2011 | Technion\nB.Sc. Industrial Engineering',
                military: '2004 - 2007 | Logistics officer',
                skills: 'P&L, KPIs, supply chain, site leadership, board reporting',
                languages: 'Hebrew (native), English (fluent)',
                references: ''
            }
        },
        emerald: {
            title: 'אמרלד עם תמונה',
            titleHe: 'אמרלד עם תמונה',
            titleEn: 'Emerald Photo',
            subHe: 'סיון ברק · ESG',
            subEn: 'Sivan Barak · ESG Lead',
            thumb: 'lay-emerald',
            layout: 'navy',
            skin: 'emerald',
            accent: '#31443b',
            font: 'Montserrat',
            bg: 'bg-preview-white',
            field: 'ops',
            preferredLang: 'he',
            he: {
                name: 'סיון ברק',
                title: 'מנהלת ESG וקיימות',
                phone: '052-6677001',
                email: 'sivan.barak@example.com',
                location: 'חיפה',
                linkedin: 'linkedin.com/in/sivanbarak',
                summary: 'מובילת קיימות עם ניסיון במדידה, דיווח וליווי הנהלה. סרגל ירוק כהה עם תמונה עגולה וציר זמן.',
                experience: '2021 - נוכחי | Verde Holdings\nמנהלת ESG\n• בניית דוח קיימות שנתי ומדדי Scope 1–2.\n• ליווי רכש בהטמעת קריטריונים לספקים.\n\n2017 - 2021 | Coastal Labs\nרכזת איכות וסביבה\n• ISO 14001, ביקורות פנימיות והדרכות צוות.',
                education: '2013 - 2017 | הטכניון\nB.Sc הנדסת סביבה',
                military: '2010 - 2012 | קצינת שלישות',
                skills: 'ESG, ISO 14001, דיווח, רכש אחראי, הדרכה',
                languages: 'עברית (שפת אם), אנגלית (גבוהה)',
                references: ''
            },
            en: {
                name: 'Sivan Barak',
                title: 'ESG and Sustainability Lead',
                phone: '052-6677001',
                email: 'sivan.barak@example.com',
                location: 'Haifa',
                linkedin: 'linkedin.com/in/sivanbarak',
                summary: 'Sustainability lead with measurement, reporting, and leadership-advisory experience. A deep green sidebar with a circular photo and timeline.',
                experience: '2021 - Present | Verde Holdings\nESG Lead\n• Built the annual sustainability report and Scope 1–2 metrics.\n• Coached procurement on supplier criteria.\n\n2017 - 2021 | Coastal Labs\nQuality and environment coordinator\n• ISO 14001, internal audits, and team training.',
                education: '2013 - 2017 | Technion\nB.Sc. Environmental Engineering',
                military: '2010 - 2012 | Personnel officer',
                skills: 'ESG, ISO 14001, reporting, responsible sourcing, training',
                languages: 'Hebrew (native), English (advanced)',
                references: ''
            }
        },
        harvard: {
            title: 'כרונולוגי ATS',
            titleHe: 'כרונולוגי ATS',
            titleEn: 'Harvard ATS',
            subHe: 'נועם שטרן · יועץ אסטרטגיה',
            subEn: 'Noam Stern · Strategy Consultant',
            thumb: 'lay-harvard',
            layout: 'classic',
            skin: '',
            accent: '#1c1917',
            font: 'Inter',
            bg: 'bg-preview-white',
            field: 'sales',
            preferredLang: 'en',
            he: {
                name: 'נועם שטרן',
                title: 'יועץ אסטרטגיה',
                phone: '050-1122448',
                email: 'noam.stern@example.com',
                location: 'תל אביב',
                linkedin: 'linkedin.com/in/noamstern',
                summary: 'יועץ עם ניסיון בפרויקטי צמיחה, תמחור ומחקר שוק. פורמט כרונולוגי נקי בסגנון Harvard — הנפוץ בעולם לגיוס תאגידי ו-ATS.',
                experience: '2021 - נוכחי | Meridian Consulting\nיועץ\n• הובלת 9 פרויקטי due diligence וגיבוש המלצות להנהלה.\n• בניית מודלי תמחור שהעלו שולי רווח ב-4 נקודות.\n\n2018 - 2021 | Northstar\nאנליסט\n• מחקר שוק, מצגות לקוח ותמיכה בצוותי מכירות.',
                education: '2014 - 2018 | האוניברסיטה העברית\nBA בכלכלה',
                military: '2011 - 2014 | קצין מודיעין',
                skills: 'אסטרטגיה, Excel, PowerPoint, מחקר שוק, סיפור נתונים',
                languages: 'עברית (שפת אם), אנגלית (שוטפת)',
                references: ''
            },
            en: {
                name: 'Noam Stern',
                title: 'Strategy Consultant',
                phone: '050-1122448',
                email: 'noam.stern@example.com',
                location: 'Tel Aviv',
                linkedin: 'linkedin.com/in/noamstern',
                summary: 'Consultant with growth, pricing, and market-research experience. A clean chronological Harvard-style resume — the most common format for corporate and ATS hiring worldwide.',
                experience: '2021 - Present | Meridian Consulting\nConsultant\n• Led 9 due-diligence projects and wrote recommendations for leadership.\n• Built pricing models that lifted margin by 4 points.\n\n2018 - 2021 | Northstar\nAnalyst\n• Market research, client decks, and sales-team support.',
                education: '2014 - 2018 | Hebrew University\nBA in Economics',
                military: '2011 - 2014 | Intelligence officer',
                skills: 'Strategy, Excel, PowerPoint, market research, data storytelling',
                languages: 'Hebrew (native), English (fluent)',
                references: ''
            }
        },
        europass: {
            title: 'אירופה / Europass',
            titleHe: 'אירופה / Europass',
            titleEn: 'European CV',
            subHe: 'לין כהן · רכזת פרויקטים',
            subEn: 'Lin Cohen · Project Coordinator',
            thumb: 'lay-europass',
            layout: 'azure',
            skin: '',
            accent: '#3d5a6c',
            font: 'Heebo',
            bg: 'bg-preview-white',
            field: 'ops',
            preferredLang: 'en',
            he: {
                name: 'לין כהן',
                title: 'רכזת פרויקטים בינלאומיים',
                phone: '053-8801122',
                email: 'lin.cohen@example.com',
                location: 'ברלין / תל אביב',
                linkedin: 'linkedin.com/in/lincohen',
                summary: 'רכזת פרויקטים עם ניסיון בתוכניות אירופיות, דיווח למענקים ושפות. מבנה בסגנון Europass: כותרת ברורה, כישורים ושפות במקום בולט.',
                experience: '2020 - נוכחי | Horizon Desk\nרכזת פרויקטים\n• תיאום 6 שותפים בתוכנית Erasmus+ ודיווח תקציבי בזמן.\n• כתיבת דוחות ביניים וליווי ביקורות.\n\n2017 - 2020 | Civic Lab\nעוזרת מחקר\n• איסוף נתונים, תרגום ולוחות זמנים לצוות רב־לאומי.',
                education: '2013 - 2017 | Sciences Po\nBA במדעי המדינה',
                military: '2010 - 2012 | מש"קית חינוך',
                skills: 'ניהול פרויקטים, דיווח מענקים, Excel, תרגום, תיאום שותפים',
                languages: 'עברית (שפת אם), אנגלית (C1), צרפתית (B2), גרמנית (B1)',
                references: ''
            },
            en: {
                name: 'Lin Cohen',
                title: 'International Project Coordinator',
                phone: '053-8801122',
                email: 'lin.cohen@example.com',
                location: 'Berlin / Tel Aviv',
                linkedin: 'linkedin.com/in/lincohen',
                summary: 'Project coordinator with European programmes, grant reporting, and languages. A Europass-inspired structure: clear header, skills and languages in a prominent column.',
                experience: '2020 - Present | Horizon Desk\nProject Coordinator\n• Coordinated 6 Erasmus+ partners and filed budget reports on time.\n• Wrote interim reports and supported audits.\n\n2017 - 2020 | Civic Lab\nResearch assistant\n• Data collection, translation, and timelines for a multinational team.',
                education: '2013 - 2017 | Sciences Po\nBA in Political Science',
                military: '2010 - 2012 | Education NCO',
                skills: 'Project coordination, grant reporting, Excel, translation, partner management',
                languages: 'Hebrew (native), English (C1), French (B2), German (B1)',
                references: ''
            }
        },
        clinic: {
            title: 'בריאות וקליניקה',
            titleHe: 'בריאות וקליניקה',
            titleEn: 'Healthcare',
            subHe: 'יעל מזרחי · אחות',
            subEn: 'Yael Mizrahi · Registered Nurse',
            thumb: 'lay-clinic',
            layout: 'azure',
            skin: 'mint',
            accent: '#2f6f6a',
            font: 'Assistant',
            bg: 'bg-preview-mint',
            field: 'healthcare',
            preferredLang: 'he',
            he: {
                name: 'יעל מזרחי',
                title: 'אחות מוסמכת · מחלקה פנימית',
                phone: '052-3344556',
                email: 'yael.mizrahi@example.com',
                location: 'פתח תקווה',
                linkedin: 'linkedin.com/in/yaelmizrahi',
                summary: 'אחות מוסמכת עם ניסיון במחלקה פנימית, תיעוד קליני וליווי מטופלים. פורמט רגוע ונפוץ למקצועות הבריאות.',
                experience: '2020 - נוכחי | בית חולים בילינסון\nאחות מוסמכת\n• טיפול ב-12–14 מטופלים במשמרת ותיעוד מדויק ב-EMR.\n• הדרכת מטופלים ומשפחות לשחרור בטוח.\n\n2017 - 2020 | קופת חולים כללית\nאחות בקהילה\n• חיסונים, מעקב כרוני ותיאום עם רופאי משפחה.',
                education: '2013 - 2017 | אוניברסיטת תל אביב\nB.S.N סיעוד',
                military: '2010 - 2012 | חובשת',
                skills: 'סיעוד, EMR, ACLS, תקשורת עם מטופלים, עבודת צוות',
                languages: 'עברית (שפת אם), אנגלית (מקצועית), ערבית (בסיסית)',
                references: ''
            },
            en: {
                name: 'Yael Mizrahi',
                title: 'Registered Nurse · Internal Medicine',
                phone: '052-3344556',
                email: 'yael.mizrahi@example.com',
                location: 'Petah Tikva',
                linkedin: 'linkedin.com/in/yaelmizrahi',
                summary: 'Registered nurse with internal-medicine, clinical documentation, and patient-education experience. A calm layout common in healthcare applications.',
                experience: '2020 - Present | Beilinson Hospital\nRegistered Nurse\n• Cared for 12–14 patients per shift with accurate EMR notes.\n• Educated patients and families for safe discharge.\n\n2017 - 2020 | Clalit Health Services\nCommunity nurse\n• Vaccinations, chronic follow-up, and coordination with family doctors.',
                education: '2013 - 2017 | Tel Aviv University\nB.S.N. Nursing',
                military: '2010 - 2012 | Combat medic',
                skills: 'Nursing, EMR, ACLS, patient communication, teamwork',
                languages: 'Hebrew (native), English (professional), Arabic (basic)',
                references: ''
            }
        },
        gold: {
            title: 'זהב פיננסי',
            titleHe: 'זהב פיננסי',
            titleEn: 'Finance Gold',
            subHe: 'עידו שמש · בנקאות',
            subEn: 'Ido Shemesh · Banking',
            thumb: 'lay-gold',
            layout: 'executive',
            skin: '',
            accent: '#3e342c',
            font: 'Frank Ruhl Libre',
            bg: 'bg-preview-cream',
            field: 'finance',
            preferredLang: 'he',
            he: {
                name: 'עידו שמש',
                title: 'מנהל לקוחות עסקיים · בנקאות',
                phone: '054-7788990',
                email: 'ido.shemesh@example.com',
                location: 'רמת גן',
                linkedin: 'linkedin.com/in/idoshemesh',
                summary: 'בנקאי עסקי עם ניסיון באשראי, שימור לקוחות וצמיחת תיק. כותרת כהה עם קו זהב — פורמט נפוץ לפיננסים והנהלה.',
                experience: '2019 - נוכחי | בנק מסחרי\nמנהל לקוחות עסקיים\n• ניהול תיק של 80 חברות והגדלת אשראי איכותי ב-22%.\n• בניית תוכניות מימון מול מחלקת סיכונים.\n\n2015 - 2019 | בית השקעות\nיועץ השקעות\n• ליווי לקוחות פרטיים בתיקי השקעות ודיווח רבעוני.',
                education: '2011 - 2015 | המרכז הבינתחומי\nBA בכלכלה ומנהל עסקים',
                military: '2008 - 2011 | קצין קשר',
                skills: 'אשראי, ניתוח דוחות, CRM, משא ומתן, רגולציה',
                languages: 'עברית (שפת אם), אנגלית (מקצועית)',
                references: ''
            },
            en: {
                name: 'Ido Shemesh',
                title: 'Corporate Relationship Manager · Banking',
                phone: '054-7788990',
                email: 'ido.shemesh@example.com',
                location: 'Ramat Gan',
                linkedin: 'linkedin.com/in/idoshemesh',
                summary: 'Corporate banker with credit, retention, and book-growth experience. A dark header with a gold rule — a common format in finance and leadership.',
                experience: '2019 - Present | Commercial Bank\nCorporate Relationship Manager\n• Managed 80 companies and grew quality credit 22%.\n• Built financing plans with the risk team.\n\n2015 - 2019 | Investment house\nInvestment advisor\n• Advised private clients on portfolios and quarterly reporting.',
                education: '2011 - 2015 | Reichman University\nBA in Economics and Business',
                military: '2008 - 2011 | Signals officer',
                skills: 'Credit, financial analysis, CRM, negotiation, regulation',
                languages: 'Hebrew (native), English (professional)',
                references: ''
            }
        },
        cobalt: {
            title: 'קובלט הייטק',
            titleHe: 'קובלט הייטק',
            titleEn: 'Cobalt Tech',
            subHe: 'רן אביב · DevOps',
            subEn: 'Ran Aviv · DevOps',
            thumb: 'lay-cobalt',
            layout: 'modern',
            skin: '',
            accent: '#3e4c58',
            font: 'IBM Plex Sans Hebrew',
            bg: 'bg-preview-pearl',
            field: 'tech',
            preferredLang: 'he',
            he: {
                name: 'רן אביב',
                title: 'מהנדס DevOps',
                phone: '050-9988001',
                email: 'ran.aviv@example.com',
                location: 'תל אביב',
                linkedin: 'linkedin.com/in/ranaviv',
                summary: 'מהנדס DevOps עם דגש על CI/CD, ענן ויציבות ייצור. פריסה מודרנית כחולה־אפורה — מהפורמטים הנפוצים להייטק.',
                experience: '2022 - נוכחי | Nimbus Cloud\nמהנדס DevOps\n• בניית pipelines ב-GitHub Actions וקיצור זמן שחרור מ-40 דקות ל-8.\n• ניטור, עלויות ענן וליווי צוותי פיתוח.\n\n2019 - 2022 | Stackyard\nSysadmin / DevOps\n• Terraform, Docker וטיפול באירועי ייצור.',
                education: '2015 - 2019 | אוניברסיטת בן-גוריון\nB.Sc מדעי המחשב',
                military: '2012 - 2015 | ממר"ם',
                skills: 'AWS, Terraform, Docker, Kubernetes, CI/CD, Python',
                languages: 'עברית (שפת אם), אנגלית (טכנית גבוהה)',
                references: ''
            },
            en: {
                name: 'Ran Aviv',
                title: 'DevOps Engineer',
                phone: '050-9988001',
                email: 'ran.aviv@example.com',
                location: 'Tel Aviv',
                linkedin: 'linkedin.com/in/ranaviv',
                summary: 'DevOps engineer focused on CI/CD, cloud, and production reliability. A modern blue-gray layout — a common tech hiring format.',
                experience: '2022 - Present | Nimbus Cloud\nDevOps Engineer\n• Built GitHub Actions pipelines and cut release time from 40 minutes to 8.\n• Owned monitoring, cloud cost, and developer support.\n\n2019 - 2022 | Stackyard\nSysadmin / DevOps\n• Terraform, Docker, and production incident response.',
                education: '2015 - 2019 | Ben-Gurion University\nB.Sc. Computer Science',
                military: '2012 - 2015 | Mamram',
                skills: 'AWS, Terraform, Docker, Kubernetes, CI/CD, Python',
                languages: 'Hebrew (native), English (professional)',
                references: ''
            }
        }
    };

    var ORDER = [
        'simple', 'charcoal', 'navy', 'petra', 'azure', 'mint',
        'ivory', 'ink', 'blush', 'espresso', 'sage',
        'slate', 'wine', 'forest', 'terracotta', 'cream',
        'sand', 'pearl', 'swiss', 'compact', 'intern',
        'academic', 'split', 'midnight', 'emerald', 'harvard',
        'europass', 'clinic', 'gold', 'cobalt'
    ];

    global.QCTemplates = TEMPLATES;
    global.QCTemplateOrder = ORDER;
})(window);
